# Generated by Django 4.1.7 on 2023-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Produto', models.CharField(max_length=20)),
                ('Des_Produto', models.CharField(max_length=30)),
            ],
        ),
    ]
